name: dsr_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  nb_utils: ^5.0.5
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.17
  country_picker: 2.0.19


  #STATE MANAGEMENT
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5

  #Firebase
  firebase_database: ^10.0.10
  firebase_core: ^2.5.0
  firebase_crashlytics: ^3.0.12
  firebase_auth: ^4.2.6
  firebase_storage: ^11.0.11
  firebase_remote_config: ^3.0.10
  cloud_firestore: ^4.3.2
  firebase_pagination: ^3.0.0
  flutter_slidable: ^2.0.0
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - assets/

