name: dsr_admin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  nb_utils: ^5.0.5
  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.3
  shared_preferences: ^2.0.17

  #STATE MANAGEMENT
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5

  #Firebase
  firebase_core: ^1.24.0
  firebase_crashlytics: ^2.9.0
  firebase_auth: ^3.11.2
  firebase_storage: ^10.3.11
  firebase_database: ^9.1.7
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^3.5.1






dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.1.1
  build_runner: ^2.3.3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter:

  uses-material-design: true

  assets:
    - assets/

