// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs5D6a3g2tl0WtCAyfHfLNSKBvIDpHM1w',
    appId: '1:191484624646:android:18695d517728f6c7baa887',
    messagingSenderId: '191484624646',
    projectId: 'dsr-flutter',
    storageBucket: 'dsr-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGlOkKHnXjfdcO3Jdrho17VVNOLOIrLP4',
    appId: '1:191484624646:ios:e3280a97473d9892baa887',
    messagingSenderId: '191484624646',
    projectId: 'dsr-flutter',
    storageBucket: 'dsr-flutter.appspot.com',
    androidClientId: '191484624646-avfu46hq7jkev8iae54iu5ocqjfs9jsu.apps.googleusercontent.com',
    iosClientId: '191484624646-6fm55kb2hsq5ba4sf09vv5kk3unmiavu.apps.googleusercontent.com',
    iosBundleId: 'com.example.dsrAdmin',
  );
}
